version: '3.8'
    
services:
  nginx:
    image: hansenwu/nginx-ea
    container_name: nginx-ea
    ports: 
     - "80:80"
  aiortc:
    image: hansenwu/webrtc-server
    container_name: ea-server
    command: "uvicorn main:app --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
  janus:
    image: canyan/janus-gateway:latest
    container_name: janus
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8088:8088"